CRM/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # crm相关业务
    url(r'^crm/', include('sales.urls')),

]

sales/models.py
from django.db import models

# Create your models here.

# from django.contrib import auth
# from django.core.exceptions import PermissionDenied
# from django.contrib.auth.models import AbstractUser, PermissionsMixin, BaseUserManager, User
# from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'python高级全栈开发'))

class_type_choices = (('fulltime', '脱产班'),
                      ('online', '网络班'),
                      ('weekend', '周末班'))

source_type = (('qq', 'qq群'),
               ('referral', '内部转介绍'),
               ('website', '官方网站'),
               ('baidu_ads', '百度推广'),
               ('office_direct', '直接上门'),
               ('WoM', '口碑'),
               ('public_class', '公开课'),
               ('website_friends', '友链'),
               ('other', '其他'),
               )

enroll_status_choices = (('singed', '已报名'),
                         ('unregistered', '未报名'),
                         ('studying', '学习中'),
                         ('paid_in_full', '学费已交齐'),
                         )

seek_status_choices = (
    ('A', '近期无报名计划'),
    ('B', '1个月内报名'),
    ('C', '2周内报名'),
    ('D', '1周内报名'),
    ('E', '定金'),
    ('F', '到班'),
    ('G', '全款'),
    ('H', '无效'),
)

pay_type_choices = (
    ('deposit', '定金/报名费'),
    ('tuition', '学费'),
    ('transfer', '转班'),
    ('dropout', '退学'),
    ('refund', '退款'),
)

attendance_choices = (
    ('checked', '已签到'),
    ('vacate', '请假'),
    ('late', '迟到'),
    ('absence', '缺勤'),
    ('leave_early', '早退'),
)

score_choices = (
    (100, 'A+'),
    (90, 'A'),
    (85, 'B+'),
    (80, 'B'),
    (70, 'B-'),
    (60, 'C+'),
    (50, 'C'),
    (40, 'C-'),
    (0, 'D'),
    (-1, 'N/A'),
    (-100, 'COPY'),
    (-1000, 'FALL'),
)


class UserInfo(models.Model):
    """
    用户表:销售
    """
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=32)
    email = models.EmailField()
    telephone = models.CharField(max_length=32, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.username


class Customer(models.Model):
    """
    客户信息表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    gender_type = (
        ('male', '男'),
        ('female', '女'),
    )
    gender = models.CharField('性别', choices=gender_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text='格式yyyy-mm-dd', blank=True, null=True)
    phone = models.CharField('手机号', blank=True, null=True, max_length=20)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name='转介绍自学员', blank=True, null=True, on_delete=models.CASCADE)  # self 指的就是自己这张表, 与models.ForeignKey('Customer', verbose_name='转介绍自学员', blank=True, null=True, on_delete=models.CASCADE)是一样的效果
    course = MultiSelectField('咨询课程', choices=course_choices)  # 多选，存成一个列表的格式，不用多选，也可以用 CharField也存储
    class_type = models.CharField('班级类型', max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField('客户备注', blank=True, null=True)
    status = models.CharField('状态', choices=enroll_status_choices, max_length=64, default='unregistered', help_text='选择客户此时的状态')
    date = models.DateTimeField('咨询日期', auto_now_add=True)
    last_consult_date = models.DateField('最后跟进日期', auto_now_add=True)
    next_date = models.DateField('预计再次跟进时间', blank=True, null=True)

    # 用户表中存放的是自己公司的所有员工
    consultant = models.ForeignKey('UserInfo', verbose_name='销售', related_name='customers', blank=True, null=True, on_delete=models.CASCADE)

    # 一个客户可以报多个班，报个脱产班，再报周末班等，所以是多对多的关系
    class_list = models.ManyToManyField('ClassList', verbose_name='已报班级', blank=True)

    class Meta:
        ordering = ['id']  # 所有的字段都按照id正向排列
        verbose_name = '客户信息表'  # admin中使用的，以复数的形式展示，加s，客户信息表s
        verbose_name_plural = '客户信息表'  # 不加s

    def __str__(self):
        return self.name + ':' + self.qq

    def status_show(self):
        status_color = {
            'singed': 'pink',
            'unregistered': 'red',
            'studying': 'yellow',
            'paid_in_full': 'gray',
        }
        return mark_safe("<span style='background-color:{0}'>{1}</span>".format(status_color[self.status], self.get_status_display()))

    def get_classlist(self):
        l = []
        for cls in self.class_list.all():  # 通过self.get_classlist的时候，拿到了所有的班级信息，前端显示的时候用
            l.append(str(cls))
        return mark_safe(','.join(l))  # 纯文本，不用mark_safe也可以


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField('课程名称', max_length=64, choices=course_choices)
    semester = models.IntegerField('学期')
    campuses = models.ForeignKey('Campuses', verbose_name='校区', on_delete=models.CASCADE)
    price = models.IntegerField('学费', default=10000)
    memo = models.CharField('说明', max_length=100, blank=True, null=True)
    start_date = models.DateField('开班日期')
    graduate_date = models.DateField('结业日期', blank=True, null=True)
    teachers = models.ManyToManyField('UserInfo', verbose_name='老师')
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True, null=True)

    class Meta:
        unique_together = ('course', 'semester', 'campuses')  # 联合唯一

    def __str__(self):
        return '{}{}{}'.format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name='所咨询客户')
    note = models.TextField('跟进内容')
    status = models.CharField('跟进状态', max_length=8, choices=seek_status_choices, help_text='选择客户此时的状态')
    consultant = models.ForeignKey('UserInfo', verbose_name='跟进人', related_name='records')
    date = models.DateTimeField('跟进日期', auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    # 表面上删除了这个数据，其实数据库里面还有

    def __str__(self):
        return str(self.customer) + str(self.consultant)


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField('为什么报名', max_length=1024, default=None, blank=True, null=True)
    your_exception = models.TextField('学完想要达成的具体期望', max_length=1024, blank=True, null=True)
    contract_approved = models.BooleanField('审批通过', help_text='在审阅完学员的资料无误后勾选此项，合同即生效', default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name='报名日期')
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrollment_class = models.ForeignKey('ClassList', verbose_name='所报班级')

    class Meta:
        unique_together = ('enrollment_class', 'customer')  # 班级和客户联一，一个班级只能有同一个学生

    def __str__(self):
        return self.customer.name


class CourseRecord(models.Model):
    """
    课程记录表
    """
    day_num = models.IntegerField('节次', help_text='此处填写第几节课或第几天课程...,必须为数字')
    date = models.DateField(auto_now_add=True, verbose_name='上课日期')
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name='本节课程有作业')
    home_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name='班级')
    teacher = models.ForeignKey('UserInfo', verbose_name='讲师')

    class Meta:
        unique_together = ('re_class', 'day_num')

    def __str__(self):
        return str(self.day_num)


class StudyRecord(models.Model):
    """
    学习记录表
    """
    attendance = models.CharField('考勤', choices=attendance_choices, default='checked', max_length=64)
    score = models.IntegerField('本节成绩', choices=score_choices, default=1)
    homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.CharField('备注', max_length=255, blank=True, null=True)
    homework = models.FileField('作业文件', blank=True, null=True, default=None)
    course_record = models.ForeignKey('CourseRecord', verbose_name='某节课程')
    student = models.ForeignKey('Customer', verbose_name='学员')

    class Meta:
        unique_together = ('course_record', 'student')

    def __str__(self):
        return self.student.name + ':' + str(self.course_record.day_num)

templates/saleshtml/add_customer.html
{% extends 'base.html' %}

{% block title %}
    <h1>
        {{ label }}
        <small>可以添加客户记录</small>
    </h1>
{% endblock %}

{% block content %}

    <form class="form-horizontal" method="post" novalidate>
        {% csrf_token %}
        {% for field in customer_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                </div>
                <div class="col-sm-2">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}
        <button class="btn btn-success">提交</button>
    </form>


{% endblock %}

templates/saleshtml/add_edit_consult.html
{% extends 'base.html' %}
{% block title %}
            <h1>
                {{ label }}
                <small>可以更新客户信息</small>
            </h1>
            {% endblock %}
{% block content %}

    <form class="form-horizontal" method="post" novalidate>
    {% csrf_token %}
        {% for field in consult_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                </div>
                <div class="col-sm-2">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}
    <button class="btn btn-success">提交</button>
    </form>


{% endblock %}

templates/saleshtml/add_edit_enroll.html
{% extends 'base.html' %}
{% block title %}
            <h1>
                {{ label }}
                <small>可以更新客户信息</small>
            </h1>
            {% endblock %}
{% block content %}

    <form class="form-horizontal" method="post" novalidate>
    {% csrf_token %}
        {% for field in enroll_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                </div>
                <div class="col-sm-2">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}
    <button class="btn btn-success">提交</button>
    </form>


{% endblock %}

templates/saleshtml/consult_record.html
{% extends 'base.html' %}
{% block title %}
    <h1>
{#        {% if tag == '1' %}#}
{#            公户信息{{ request }}--{{ request.path }}#}
{#        {% else %}#}
{#            我的客户信息#}
{#        {% endif %}#}
    {% load mytags %}
{#    {% reverse_url request %}#}
    跟进记录展示
    </h1>
{% endblock %}

{% block content %}
    <a href="{% url 'add_consult_record' %}" class="btn btn-primary">添加跟进记录</a>
    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="customer__name__contains">客户名称</option>
                </select>
                <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
                <button type="submit" class="btn btn-default">搜索🔍</button>
            </div>
        </form>

    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group pull-left">
            <select name="action" id="action" class="form-control">
                <option value="bulk_delete">批量删除</option>
            </select>
        </div>
        <button class="btn btn-warning">go</button>

        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th><input type="checkbox" name="select_all"> 选择</th>
                <th>序号</th>
                <th>所咨询客户</th>
                <th>跟进内容</th>
                <th>跟进状态</th>
                <th>跟进人</th>
                <th>跟进日期</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for consult in consult_list %}
                <tr>
                    <td><input type="checkbox" name="cids" value="{{ consult.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ consult.customer }}</td>
                    <td>{{ consult.note }}</td>
                    <td>{{ consult.get_status_display }}</td>
                    <td>{{ consult.consultant }}</td>
                    <td>{{ consult.date|date:'Y-m-d H:i:s' }}</td>
                    <td>{{ consult.consultant|default:'暂无' }}</td>
                    <td>
{#                        <a href="{% url 'edit_customer' customer.pk %}"><i class="fa fa-edit"></i></a>#}
                        <a href="{% resole_url request 'edit_consult_record' consult.pk %}"><i class="fa fa-edit"></i></a>
                        <a href=""><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ page_html }}
    </form>
{% endblock %}

templates/saleshtml/course_record.html
{% extends 'base.html' %}
{% block title %}
    <h1>
{#        {% if tag == '1' %}#}
{#            公户信息{{ request }}--{{ request.path }}#}
{#        {% else %}#}
{#            我的客户信息#}
{#        {% endif %}#}
        课程记录
    </h1>
{% endblock %}

{% block content %}
    <a href="" class="btn btn-primary">添加课程记录</a>
    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="qq__contains">qq</option>
                    <option value="name__contains">name</option>
                </select>
                <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
                <button type="submit" class="btn btn-default">搜索🔍</button>
            </div>
        </form>

    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group pull-left">
            <select name="action" id="action" class="form-control">
                    <option value="bulk_create_study_record">批量生成学习记录</option>

            </select>
        </div>
        <button class="btn btn-warning">go</button>

        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th><input type="checkbox" name="select_all"> 选择</th>
                <th>序号</th>
                <th>节次</th>
                <th>上课日期</th>
                <th>本节课程标题</th>
                <th>班级</th>
                <th>学习记录</th>
                <th>讲师</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for course_record in course_records %}
                <tr>
                    <td><input type="checkbox" name="cids" value="{{ course_record.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ course_record.day_num }}</td>
                    <td>{{ course_record.date|date:'Y-m-d' }}</td>
                    <td>{{ course_record.course_title }}</td>
                    <td>{{ course_record.re_class }}</td>
                    <td>
                        <a href="{% url 'study_record' course_record.pk %}">查看学习记录</a>
                    </td>
                    <td>{{ course_record.teacher }}</td>
                    <td>
{#                        <a href="{% url 'edit_customer' customer.pk %}"><i class="fa fa-edit"></i></a>#}
                        <a href=""><i class="fa fa-edit"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ page_html }}
    </form>

    {#<nav aria-label="Page navigation">#}
    {#  <ul class="pagination">#}
    {#    <li>#}
    {#      <a href="#" aria-label="Previous">#}
    {#        <span aria-hidden="true">&laquo;</span>#}
    {#      </a>#}
    {#    </li>#}
    {#      {% for i in page_num_count %}#}
    {#      <li><a href="/customer/?page={{ i }}">{{ i }}</a></li>#}
    {#      {% endfor %}#}

    {#    <li>#}
    {#      <a href="#" aria-label="Next">#}
    {#        <span aria-hidden="true">&raquo;</span>#}
    {#      </a>#}
    {#    </li>#}
    {#  </ul>#}
    {#</nav>#}
{% endblock %}

templates/saleshtml/customers.html
{% extends 'base.html' %}
{% block title %}
    <h1>
{#        {% if tag == '1' %}#}
{#            公户信息{{ request }}--{{ request.path }}#}
{#        {% else %}#}
{#            我的客户信息#}
{#        {% endif %}#}
    {% load mytags %}
    {% reverse_url request %}
    </h1>
{% endblock %}

{% block content %}
    <a href="{% url 'add_customer' %}" class="btn btn-primary">添加客户</a>
    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="qq__contains">qq</option>
                    <option value="name__contains">name</option>
                </select>
                <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
                <button type="submit" class="btn btn-default">搜索🔍</button>
            </div>
        </form>

    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group pull-left">
            <select name="action" id="action" class="form-control">
                {% if tag == '1' %}
                    <option value="public_private">公户转私户</option>
                {% else %}
                    <option value="private_public">私户转公户</option>
                {% endif %}


            </select>
        </div>
        <button class="btn btn-warning">go</button>

        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th><input type="checkbox" name="select_all"> 选择</th>
                <th>序号</th>
                <th>id</th>
                <th>qq</th>
                <th>姓名</th>
                <th>性别</th>
                <th>手机号码</th>
                <th>状态</th>
                <th>客户来源</th>
                <th>跟进记录</th>
                <th>销售</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customer_obj %}
                <tr>
                    <td><input type="checkbox" name="cids" value="{{ customer.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ customer.pk }}</td>
                    <td>{{ customer.qq }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.get_gender_display }}</td>
                    <td>{{ customer.phone|default:'无' }}</td>
                    <td>{{ customer.status_show }}</td>
                    <td>{{ customer.get_source_display }}</td>
                    <td>
                        <a href="{% url 'consult_record' %}?cid={{ customer.pk }}">查看详情</a>
                    </td>
                    <td>{{ customer.consultant|default:'暂无' }}</td>
                    <td>
{#                        <a href="{% url 'edit_customer' customer.pk %}"><i class="fa fa-edit"></i></a>#}
                        <a href="{% resole_url request 'edit_customer' customer.pk %}"><i class="fa fa-edit"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ page_html }}
    </form>

    {#<nav aria-label="Page navigation">#}
    {#  <ul class="pagination">#}
    {#    <li>#}
    {#      <a href="#" aria-label="Previous">#}
    {#        <span aria-hidden="true">&laquo;</span>#}
    {#      </a>#}
    {#    </li>#}
    {#      {% for i in page_num_count %}#}
    {#      <li><a href="/customer/?page={{ i }}">{{ i }}</a></li>#}
    {#      {% endfor %}#}

    {#    <li>#}
    {#      <a href="#" aria-label="Next">#}
    {#        <span aria-hidden="true">&raquo;</span>#}
    {#      </a>#}
    {#    </li>#}
    {#  </ul>#}
    {#</nav>#}
{% endblock %}

templates/saleshtml/edit_customer.html
{% extends 'base.html' %}
{% block title %}
            <h1>
                {{ label }}
                <small>可以更新客户信息</small>
            </h1>
            {% endblock %}
{% block content %}

    <form class="form-horizontal" method="post" novalidate>
    {% csrf_token %}
        {% for field in customer_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                </div>
                <div class="col-sm-2">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}
    <button class="btn btn-success">提交</button>
    </form>


{% endblock %}

templates/saleshtml/enrollments.html
{% extends 'base.html' %}
{% block title %}
    <h1>
{#        {% if tag == '1' %}#}
{#            公户信息{{ request }}--{{ request.path }}#}
{#        {% else %}#}
{#            我的客户信息#}
{#        {% endif %}#}
    {% load mytags %}
{#    {% reverse_url request %}#}
    报名记录展示
    </h1>
{% endblock %}

{% block content %}
    <a href="{% url 'enroll_add' %}" class="btn btn-primary">添加报名记录</a>
    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="customer__name__contains">客户名称</option>
                </select>
                <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
                <button type="submit" class="btn btn-default">搜索🔍</button>
            </div>
        </form>

    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group pull-left">
            <select name="action" id="action" class="form-control">
                <option value="bulk_delete">批量删除</option>
            </select>
        </div>
        <button class="btn btn-warning">go</button>

        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th><input type="checkbox" name="select_all"> 选择</th>
                <th>序号</th>
                <th>为什么报名</th>
                <th>审批通过</th>
                <th>报名日期</th>
                <th>客户名称</th>
                <th>小区</th>
                <th>所报班级</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for enroll in enrolls %}
                <tr>
                    <td><input type="checkbox" name="cids" value="{{ enroll.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ enroll.why_us }}</td>
                    <td>{{ enroll.contract_approved }}</td>
                    <td>{{ enroll.enrolled_date|date:'Y-m-d H:i:s'  }}</td>
                    <td>{{ enroll.customer }}</td>
                    <td>{{ enroll.school }}</td>
                    <td>{{ enroll.enrollment_class }}</td>
                    <td>
{#                        <a href="{% url 'edit_customer' customer.pk %}"><i class="fa fa-edit"></i></a>#}
                        <a href="{% resole_url request 'enroll_edit' enroll.pk%}"><i class="fa fa-edit"></i></a>
                        <a href=""><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ page_html }}
    </form>
{% endblock %}

templates/saleshtml/home.html
{% extends 'base.html' %}

templates/saleshtml/study_record.html
{% extends 'base.html' %}
{% block title %}
    <h1>
        {#        {% if tag == '1' %}#}
        {#            公户信息{{ request }}--{{ request.path }}#}
        {#        {% else %}#}
        {#            我的客户信息#}
        {#        {% endif %}#}
        学习记录
    </h1>
{% endblock %}

{% block content %}
    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="qq__contains">qq</option>
                    <option value="name__contains">name</option>
                </select>
                <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
                <button type="submit" class="btn btn-default">搜索🔍</button>
            </div>
        </form>

    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        <div class="form-group pull-left">
            <select name="action" id="action" class="form-control">
                <option value="bulk_create_study_record">xx</option>

            </select>
        </div>
        <button class="btn btn-warning">go</button>
        {{ formset.errors }}
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th><input type="checkbox" name="select_all"> 选择</th>
                <th>序号</th>
                <th>考勤</th>
                <th>本节成绩</th>
                <th>作业批语</th>
                <th>某节课程</th>
                <th>学员</th>
                <th>讲师</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for field in formset %}
                <tr>
                    {{ field.id }}
                    <td><input type="checkbox" name="cids" value="{{ field.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ field.attendance }}</td>
                    <td>{{ field.score }}</td>
                    <td>{{ field.homework_note }}</td>
                    <td>{{ field.instance.course_record }}</td>
                    <td class="hidden">{{ field.course_record }}</td>
                    <td>{{ field.instance.student }}</td>
                    <td class="hidden">{{ field.student }}</td>
                    <td>
                        {#                        <a href="{% url 'edit_customer' customer.pk %}"><i class="fa fa-edit"></i></a>#}
                        <a href=""><i class="fa fa-edit"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button class="btn btn-success">提交</button>
        {{ page_html }}
    </form>

    {#<nav aria-label="Page navigation">#}
    {#  <ul class="pagination">#}
    {#    <li>#}
    {#      <a href="#" aria-label="Previous">#}
    {#        <span aria-hidden="true">&laquo;</span>#}
    {#      </a>#}
    {#    </li>#}
    {#      {% for i in page_num_count %}#}
    {#      <li><a href="/customer/?page={{ i }}">{{ i }}</a></li>#}
    {#      {% endfor %}#}

    {#    <li>#}
    {#      <a href="#" aria-label="Next">#}
    {#        <span aria-hidden="true">&raquo;</span>#}
    {#      </a>#}
    {#    </li>#}
    {#  </ul>#}
    {#</nav>#}
{% endblock %}